version: '3'

services:
  textmagic-postgres:
    build: docker/postgres
    container_name: textmagic_postgres
    ports:
      - '65438:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  textmagic-php:
    build: docker/php-fpm
    container_name: textmagic_php
    environment:
      APP_ENV: dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    volumes:
      - ./:/var/www/backend
      - ./docker/php-fpm/custom.conf:/usr/local/etc/php-fpm.d/custom.conf
      - ./docker/php-fpm/bashrc:/root/.bashrc
  textmagic-nginx:
    build: docker/nginx
    container_name: textmagic_nginx
    restart: always
    ports:
      - '2980:80'
      - '29443:443'
    volumes:
      - ./:/var/www/backend
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/hosts/textmagic.conf:/etc/nginx/conf.d/default.conf

volumes:
  ###> doctrine/doctrine-bundle ###
  pgdata:
    driver: local
###< doctrine/doctrine-bundle ###